---

- name: Launching RDS Instance
  rds:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    command: create
    region: "{{ region }}"
    multi_zone: yes
    vpc_security_groups: "{{ rds_sg }}"
    subnet: "{{ rds_name }}"
    db_engine: postgres
    db_name: "{{ db_name }}"
    engine_version: "{{ eng_version }}"
    publicly_accessible: no
    backup_retention: 7
    size: "{{ rds_size }}"
    instance_type: "{{ rds_type }}"
    instance_name: "{{ rds_name }}"
    license_model: "{{ license_type }}"
    username: "{{ rds_username }}"
    password: "{{ rds_password }}"
    iops: "{{ iops }}"
    port: "{{ rds_port }}"
    wait: yes
    wait_timeout: 2000
    tags:
      Environment: "{{ rds_environment }}"
      Application: "{{ rds_application }}"
  register: rds

- name: Display RDS endpoint 
  debug:
    msg: "The new db endpoint is {{ rds.instance.endpoint }}"
