# Setting up Infrastructure on AWS

- name: Creating virtual private cloud(VPC)
  hosts: localhost
  connection: local
  gather_facts: no
  roles:
    - VPC

- name: Setting up Ec2  Infrastucture
  hosts: localhost
  connection: local
  gather_facts: no
  roles:
    - Ec2
